name: ms
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.13
  - pip
  - pytorch-cuda=11.8
  - pytorch=2.1.2
  - tensorboard
  - wandb
  - opencv
  - pytest
  - moviepy
  - diffusers=0.25.0
  - pip:
    - mani-skill2==0.5.3
    - gymnasium==0.29.1
    - stable-baselines3==2.2.1
